spring.application.name=switch-pagos
spring.config.import=optional:file:.env[.properties]
server.port=${SERVER_PORT:8081}

# PostgreSQL
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:switch_pagos}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:123}
spring.datasource.driver-class-name=org.postgresql.Driver
app.db.auto-create=${APP_DB_AUTO_CREATE:true}

# JPA / Hibernate
spring.jpa.open-in-view=${JPA_OPEN_IN_VIEW:false}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.properties.hibernate.format_sql=${JPA_FORMAT_SQL:true}
spring.jpa.properties.hibernate.dialect=${JPA_DIALECT:org.hibernate.dialect.PostgreSQLDialect}

# Business rules
# RF-01 cutoff hour
app.ingest.cutoff-hour=${APP_INGEST_CUTOFF_HOUR:18}
# RF-01 queued batch scheduler
app.queue.processing.cron=${APP_QUEUE_PROCESSING_CRON:0 * * * * *}
# Switch clock mode: real | fixed
app.time.mode=${APP_TIME_MODE:real}
# Fixed time for demo mode
app.time.fixed-datetime=${APP_TIME_FIXED_DATETIME:}
# Time zone for real mode
app.time.zone=${APP_TIME_ZONE:America/Guayaquil}
# RF-02 duplicate window in days
app.validation.duplicate-window-days=${APP_VALIDATION_DUPLICATE_WINDOW_DAYS:30}
# RF-03 max payment amount
app.validation.max-detail-amount=${APP_VALIDATION_MAX_DETAIL_AMOUNT:5000.00}
# CORS allowed origins
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173,http://127.0.0.1:5173,https://banquito.duckdns.org,https://banco-banquito.duckdns.org,http://34.132.81.176:*}
# Core base URL
app.core.base-url=${APP_CORE_BASE_URL:http://localhost:8080}
# RF-01 Core calendar endpoint
app.core.calendar.is-business-day-endpoint=${APP_CORE_CALENDAR_IS_BUSINESS_DAY_ENDPOINT:/core/v1/holidays/is-business-day}
# RF-05 notification service
app.notification.enabled=${APP_NOTIFICATION_ENABLED:true}

# SFTP inbox poller (RF-05 canal SFTP externo)
# Set APP_SFTP_INBOX_DIR to the absolute path where el servidor SFTP deposita los archivos subidos
# Ejemplo: /home/1757158215001  o  /var/sftp/uploads
app.sftp.inbox-dir=${APP_SFTP_INBOX_DIR:}
app.sftp.poll-interval-ms=${APP_SFTP_POLL_INTERVAL_MS:30000}
app.sftp.enabled=${APP_SFTP_ENABLED:true}

# Gmail notification settings
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${GMAIL_USERNAME:notificacionbanquito@gmail.com}
spring.mail.password=${GMAIL_PASSWORD:tjntiwkdjdbgfcih}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_STARTTLS_ENABLE:true}
spring.mail.properties.mail.smtp.ssl.trust=${MAIL_SSL_TRUST:smtp.gmail.com}
