spring.application.name=switch-pagos
server.port=${SERVER_PORT:8081}

# PostgreSQL (obligatorio por variables de entorno)
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:switch_pagos}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver
app.db.auto-create=${APP_DB_AUTO_CREATE:true}

# JPA / Hibernate
spring.jpa.open-in-view=${JPA_OPEN_IN_VIEW:false}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.properties.hibernate.format_sql=${JPA_FORMAT_SQL:true}
spring.jpa.properties.hibernate.dialect=${JPA_DIALECT:org.hibernate.dialect.PostgreSQLDialect}

# Parametros de negocio por entorno
# Hora de corte para ingesta inmediata (0-23)
app.ingest.cutoff-hour=${APP_INGEST_CUTOFF_HOUR:18}
# Cron de procesamiento de lotes encolados
app.queue.processing.cron=${APP_QUEUE_PROCESSING_CRON:0 1 0 * * *}
# Tiempo del Switch para pruebas en nube: real | fixed
app.time.mode=${APP_TIME_MODE:real}
# Fecha-hora fija cuando app.time.mode=fixed, formato ISO-8601: 2026-05-14T15:00:00
app.time.fixed-datetime=${APP_TIME_FIXED_DATETIME:}
# Zona horaria usada por el Switch en modo real
app.time.zone=${APP_TIME_ZONE:America/Guayaquil}
# Ventana para detectar duplicados de archivo en dias
app.validation.duplicate-window-days=${APP_VALIDATION_DUPLICATE_WINDOW_DAYS:30}
# Monto maximo permitido por linea de pago
app.validation.max-detail-amount=${APP_VALIDATION_MAX_DETAIL_AMOUNT:5000.00}
# Origenes permitidos para frontend
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173,http://127.0.0.1:5173}
# URL del core bancario
app.core.base-url=${APP_CORE_BASE_URL:http://localhost:8080}
# Endpoint del calendario del core
app.core.calendar.is-business-day-endpoint=${APP_CORE_CALENDAR_IS_BUSINESS_DAY_ENDPOINT:/api/holidays/is-business-day}
# Servicio de notificaciones RF-05 (Gmail)
app.notification.enabled=${APP_NOTIFICATION_ENABLED:true}

# Configuración de Gmail para notificaciones
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${GMAIL_USERNAME:notificacionbanquito@gmail.com}
spring.mail.password=${GMAIL_PASSWORD:tjntiwkdjdbgfcih}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_STARTTLS_ENABLE:true}
spring.mail.properties.mail.smtp.ssl.trust=${MAIL_SSL_TRUST:smtp.gmail.com}
