spring.application.name=banquito-core
server.port=${CORE_PORT:8080}

<<<<<<< HEAD
spring.datasource.url=${DB_URL:jdbc:mariadb://localhost:3306/banquito_core?serverTimezone=America/Guayaquil&useSSL=false&allowPublicKeyRetrieval=true&disableSslHostnameVerification=true&useServerPrepStmts=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:1234}
=======
spring.datasource.url=${CORE_DATASOURCE_URL:jdbc:mariadb://localhost:3306/banquito_core?createDatabaseIfNotExist=true}
spring.datasource.username=${CORE_DATASOURCE_USERNAME:root}
spring.datasource.password=${CORE_DATASOURCE_PASSWORD:123}
>>>>>>> a3271e9 (feat: Refactor core banking integration and add business day validation)
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${CORE_JPA_DDL_AUTO:update}
spring.jpa.show-sql=${CORE_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info
